- id: trx
  name: Tron
  blockchain_key: tron-testnet
  symbol: 'T'
  type: coin
  precision: 6
  base_factor: 1_000_000
  visible: true
  deposit_enabled: true
  withdrawal_enabled: true
  min_deposit_amount: 0.1
  min_collection_amount: 0.1
  withdraw_limit_24h: 300
  withdraw_limit_72h: 600
  deposit_fee: 0
  withdraw_fee: 0
  position: 4
  options: { }

- id: trz
  name: TRONZ
  blockchain_key: tron-testnet
  symbol: 'TZ'
  type: coin
  precision: 6
  base_factor: 1_000_000
  visible: true
  deposit_enabled: true
  withdrawal_enabled: true
  min_deposit_amount: 0.1
  min_collection_amount: 0.1
  withdraw_limit_24h: 300
  withdraw_limit_72h: 600
  deposit_fee: 0
  withdraw_fee: 0
  position: 4
  options:
    trc10_token_id: '1000016'

- id: jst
  name: JUST GOV TOKEN
  blockchain_key: tron-testnet
  symbol: 'JG'
  type: coin
  precision: 18
  base_factor: 1_000_000_000_000_000_000
  visible: true
  deposit_enabled: true
  withdrawal_enabled: true
  min_deposit_amount: 0.01
  min_collection_amount: 0.01
  withdraw_limit_24h: 300
  withdraw_limit_72h: 600
  deposit_fee: 0
  withdraw_fee: 0
  position: 4
  options:
    trc20_contract_address: 'TF17BgPaZYbz8oxbjhriubPDsA7ArKoLX3'
    fee_limit: 40000000